<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7lyJnMDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7lyJnMD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7lyJnMD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::delete' => ['privates', '.service_locator.Y6j7WW_', 'get_ServiceLocator_Y6j7WWService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::edit' => ['privates', '.service_locator.Y6j7WW_', 'get_ServiceLocator_Y6j7WWService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::index' => ['privates', '.service_locator.mUjJT5m', 'get_ServiceLocator_MUjJT5mService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::new' => ['privates', '.service_locator.mUjJT5m', 'get_ServiceLocator_MUjJT5mService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::show' => ['privates', '.service_locator.R8Zt2a0', 'get_ServiceLocator_R8Zt2a0Service', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::delete' => ['privates', '.service_locator.fCPljws', 'get_ServiceLocator_FCPljwsService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::edit' => ['privates', '.service_locator.fCPljws', 'get_ServiceLocator_FCPljwsService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::index' => ['privates', '.service_locator.PIC7cpq', 'get_ServiceLocator_PIC7cpqService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::new' => ['privates', '.service_locator.PIC7cpq', 'get_ServiceLocator_PIC7cpqService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::show' => ['privates', '.service_locator.wGBnK.Z', 'get_ServiceLocator_WGBnK_ZService', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::register' => ['privates', '.service_locator.23gkdPn', 'get_ServiceLocator_23gkdPnService', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.L_5qsF9', 'get_ServiceLocator_L5qsF9Service', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:delete' => ['privates', '.service_locator.Y6j7WW_', 'get_ServiceLocator_Y6j7WWService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:edit' => ['privates', '.service_locator.Y6j7WW_', 'get_ServiceLocator_Y6j7WWService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:index' => ['privates', '.service_locator.mUjJT5m', 'get_ServiceLocator_MUjJT5mService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:new' => ['privates', '.service_locator.mUjJT5m', 'get_ServiceLocator_MUjJT5mService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:show' => ['privates', '.service_locator.R8Zt2a0', 'get_ServiceLocator_R8Zt2a0Service', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:delete' => ['privates', '.service_locator.fCPljws', 'get_ServiceLocator_FCPljwsService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:edit' => ['privates', '.service_locator.fCPljws', 'get_ServiceLocator_FCPljwsService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:index' => ['privates', '.service_locator.PIC7cpq', 'get_ServiceLocator_PIC7cpqService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:new' => ['privates', '.service_locator.PIC7cpq', 'get_ServiceLocator_PIC7cpqService', true],
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:show' => ['privates', '.service_locator.wGBnK.Z', 'get_ServiceLocator_WGBnK_ZService', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController:register' => ['privates', '.service_locator.23gkdPn', 'get_ServiceLocator_23gkdPnService', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.L_5qsF9', 'get_ServiceLocator_L5qsF9Service', true],
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::delete' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::edit' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::index' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::new' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::show' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::delete' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::edit' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::index' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::new' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::show' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::register' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:delete' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:edit' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:index' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:new' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController:show' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:delete' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:edit' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:index' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:new' => '?',
            'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController:show' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController:register' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
