<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGBnK_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wGBnK.Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wGBnK.Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'song' => ['privates', 'App\\Artists\\Domain\\Entity\\Song', 'getSongService', true],
        ], [
            'song' => 'App\\Artists\\Domain\\Entity\\Song',
        ]);
    }
}
