<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_H3IyBeoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.h3IyBeo' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Customers/Application/MessageHandler/FindUserQueryHandler.php';

        return $container->privates['.messenger.handler_descriptor.h3IyBeo'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Customers\Application\MessageHandler\FindUserQueryHandler(($container->privates['App\\Customers\\Domain\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))), []);
    }
}
