<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_2oRxskeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.2oRxske' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Customers/Application/MessageHandler/StoreUserHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['.messenger.handler_descriptor.2oRxske'])) {
            return $container->privates['.messenger.handler_descriptor.2oRxske'];
        }

        return $container->privates['.messenger.handler_descriptor.2oRxske'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Customers\Application\MessageHandler\StoreUserHandler($a), []);
    }
}
