<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_RjbE1WLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.rjbE1WL' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Customers/Application/MessageHandler/PrepareArtistUser.php';

        return $container->privates['.messenger.handler_descriptor.rjbE1WL'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Customers\Application\MessageHandler\PrepareArtistUser(), []);
    }
}
