<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PIC7cpqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PIC7cpq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PIC7cpq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'songRepository' => ['privates', 'App\\Artists\\Domain\\Repository\\SongRepository', 'getSongRepositoryService', true],
        ], [
            'songRepository' => 'App\\Artists\\Domain\\Repository\\SongRepository',
        ]);
    }
}
