<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Artists\Infrastructure\Symfony\Form\AlbumType' shared autowired service.
     *
     * @return \App\Artists\Infrastructure\Symfony\Form\AlbumType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Artists/Infrastructure/Symfony/Form/AlbumType.php';

        return $container->privates['App\\Artists\\Infrastructure\\Symfony\\Form\\AlbumType'] = new \App\Artists\Infrastructure\Symfony\Form\AlbumType();
    }
}
