<?php

namespace ContainerDzr6eXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSongService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Artists\Domain\Entity\Song' shared autowired service.
     *
     * @return \App\Artists\Domain\Entity\Song
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Artists/Domain/Entity/Song.php';

        return $container->privates['App\\Artists\\Domain\\Entity\\Song'] = new \App\Artists\Domain\Entity\Song();
    }
}
