<?php

namespace ContainerDK4Mky0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y6j7WWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y6j7WW_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y6j7WW_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'album' => ['privates', 'App\\Artists\\Domain\\Entity\\Album', 'getAlbumService', true],
            'albumRepository' => ['privates', 'App\\Artists\\Domain\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
        ], [
            'album' => 'App\\Artists\\Domain\\Entity\\Album',
            'albumRepository' => 'App\\Artists\\Domain\\Repository\\AlbumRepository',
        ]);
    }
}
