<?php

namespace ContainerDK4Mky0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_SQ4R5faService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.sQ4R5fa' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Customers/Application/MessageHandler/UserRegistrationSendEmailHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Customers/Infrastructure/Symfony/Security/EmailVerifier.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfonycasts/verify-email-bundle/src/VerifyEmailHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfonycasts/verify-email-bundle/src/VerifyEmailHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfonycasts/verify-email-bundle/src/Util/VerifyEmailQueryUtility.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfonycasts/verify-email-bundle/src/Generator/VerifyEmailTokenGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['.messenger.handler_descriptor.sQ4R5fa'])) {
            return $container->privates['.messenger.handler_descriptor.sQ4R5fa'];
        }
        $b = ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService());

        if (isset($container->privates['.messenger.handler_descriptor.sQ4R5fa'])) {
            return $container->privates['.messenger.handler_descriptor.sQ4R5fa'];
        }
        $c = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['.messenger.handler_descriptor.sQ4R5fa'])) {
            return $container->privates['.messenger.handler_descriptor.sQ4R5fa'];
        }
        $d = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['.messenger.handler_descriptor.sQ4R5fa'])) {
            return $container->privates['.messenger.handler_descriptor.sQ4R5fa'];
        }

        return $container->privates['.messenger.handler_descriptor.sQ4R5fa'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Customers\Application\MessageHandler\UserRegistrationSendEmailHandler(new \App\Customers\Infrastructure\Symfony\Security\EmailVerifier(new \SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelper(($container->services['router'] ?? $container->getRouterService()), new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET'), 'signature'), new \SymfonyCasts\Bundle\VerifyEmail\Util\VerifyEmailQueryUtility(), new \SymfonyCasts\Bundle\VerifyEmail\Generator\VerifyEmailTokenGenerator($container->getEnv('APP_SECRET')), 3600), new \Symfony\Component\Mailer\Mailer($a, $b, $c), $d)), []);
    }
}
