<?php

namespace ContainerDK4Mky0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MUjJT5mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mUjJT5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mUjJT5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'albumRepository' => ['privates', 'App\\Artists\\Domain\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
        ], [
            'albumRepository' => 'App\\Artists\\Domain\\Repository\\AlbumRepository',
        ]);
    }
}
