<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzr6eXa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzr6eXa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDzr6eXa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDzr6eXa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDzr6eXa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dzr6eXa',
    'container.build_id' => 'e0e709e6',
    'container.build_time' => 1682607419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzr6eXa');
