<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Customers\\Infrastructure\\Symfony\\Controller\\HomepageController::index'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Customers\\Infrastructure\\Symfony\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Customers\\Infrastructure\\Symfony\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_album_index' => [[], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::index'], [], [['text', '/album/']], [], [], []],
    'app_album_new' => [[], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::new'], [], [['text', '/album/new']], [], [], []],
    'app_album_show' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_edit' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_album_delete' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\AlbumController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/album']], [], [], []],
    'app_song_index' => [[], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::index'], [], [['text', '/song/']], [], [], []],
    'app_song_new' => [[], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::new'], [], [['text', '/song/new']], [], [], []],
    'app_song_show' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/song']], [], [], []],
    'app_song_edit' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/song']], [], [], []],
    'app_song_delete' => [['id'], ['_controller' => 'App\\Artists\\Infrastructure\\Symfony\\Controller\\SongController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/song']], [], [], []],
];
